#!/bin/bash

createSymlink() {
    if [ "$2" ]; then
        rm "$2"
    fi
    ln -s "$1" "$2"
    echo "Created symlink to $1"
}

createCodeSymlink() {
    createSymlink `pwd`$1 ~LibraryApplication\ SupportCodeUser$1
}

installExtension() {
    code --install-extension $1
}

uninstallExtension() {
    code --uninstall-extension $1
}

createCodeSymlink settings.json
createCodeSymlink keybindings.json

installExtension DavidAnson.vscode-markdownlint
installExtension Gimly81.matlab
installExtension JuanBlanco.solidity
installExtension PeterJausovec.vscode-docker
installExtension RobinMalfait.prettier-eslint-vscode
installExtension Tyriar.sort-lines
installExtension christian-kohler.npm-intellisense
installExtension christian-kohler.path-intellisense
installExtension dbaeumer.vscode-eslint
installExtension dkundel.vscode-npm-source
installExtension donjayamanne.githistory
installExtension donjayamanne.python
installExtension eamodio.gitlens
installExtension eg2.tslint
installExtension eg2.vscode-npm-script
installExtension emilast.LogFileHighlighter
installExtension fknop.vscode-npm
installExtension flowtype.flow-for-vscode
installExtension lukehoban.go
installExtension mkxml.vscode-filesize
installExtension naumovs.color-highlight
installExtension pthorsson.vscode-jsp
installExtension redhat.java
installExtension waderyan.gitblame
installExtension wix.vscode-import-cost
installExtension yzane.markdown-pdf
